<?php

define('USE_DEVELOPMENT_REPOSITORY_FOR_ALL', env('USE_DEVELOPMENT_REPOSITORY_FOR_ALL', false));
define('USE_DEVELOPMENT_REPOSITORY_FOR_DAILY_MESSAGES', env('USE_DEVELOPMENT_REPOSITORY_FOR_DAILY_MESSAGES', false));
